version: '3.1'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: react-app
    environment:
      - WATCHPACK_=value
    networks:
      - mern-app
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - mern-app
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo
    networks:
      - mern-app
    volumes:
      - mongoData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=auth

networks:
  mern-app:
    driver: bridge

volumes:
  mongoData:
